
[project]
name = "my_project"
version = "1.0.0"
description = "A sample project using Aeon"
authors = ["Your Name <your.email@example.com>"]


[settings]
admin = true
debug = true



[database]
type = "sqlite"
path = "db.sqlite"



[dependencies]